version: "3"
services:
    spark-master:
        image: bde2020/spark-master:3.1.1-hadoop3.2
        container_name: spark-master
        ports:
        - "8080:8080"
        - "7077:7077"
        environment:
        - INIT_DAEMON_STEP=setup_spark
        - TZ=Asia/Taipei
        volumes:
            - ./test:/test
    spark-worker-1:
        image: bde2020/spark-worker:3.1.1-hadoop3.2
        container_name: spark-worker-1
        depends_on:
        - spark-master
        ports:
        - "8081:8081"
        environment:
            SPARK_MASTER: spark://spark-master:7077
            SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY}
            SPARK_WORKER_CORES: 2
            TZ: "Asia/Taipei"
    spark-worker-2:
        image: bde2020/spark-worker:3.1.1-hadoop3.2
        container_name: spark-worker-2
        depends_on:
        - spark-master
        ports:
        - "8082:8081"
        environment:
            SPARK_MASTER: spark://spark-master:7077
            SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY}
            SPARK_WORKER_CORES: 2
            TZ: "Asia/Taipei"
    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes:
            - ./db:/data/db
            - ./scripts:/docker-entrypoint-initdb.d:ro
        restart: always
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            TZ: "Asia/Taipei"
    mongodb-express:
        image: mongo-express:latest
        container_name: mongodb-express
        restart: always
        depends_on:
            - mongodb
        ports:
            - 8083:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
            ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
            ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
            TZ: "Asia/Taipei"
